### ISSUE TITLE
error[E0599]: no method named `force_pretty` found for struct `reverie::Backtrace` 

### ISSUE THREAD

**Issue by androm3da** [facebookexperimental/hermit#31]
Build failure -- introduced in 299701ff7dee25d63c1b9344364b49fe56f36380 ?

```
$ cargo build --release && ./target/release/hermit run ls
warning: skipping duplicate package `main` found at `/local/mnt/workspace/install/rust/git/checkouts/reverie-9a587e40a0d7d3be/6f03658/experimental/traceviz`
   Compiling detcore v0.0.0 (/local/mnt/workspace/vp/hermit/detcore)
warning: the feature `map_first_last` has been stable since 1.66.0 and no longer requires an attribute to enable
  --> detcore/src/lib.rs:12:12
   |
12 | #![feature(map_first_last)]
   |            ^^^^^^^^^^^^^^
   |
   = note: `#[warn(stable_features)]` on by default

error[E0599]: no method named `force_pretty` found for struct `reverie::Backtrace` in the current scope
    --> detcore/src/tool_global.rs:1466:48
     |
1466 |         serde_json::to_writer(file, &backtrace.force_pretty()).unwrap();
     |                                                ^^^^^^^^^^^^ help: there is a method with a similar name: `pretty`

For more information about this error, try `rustc --explain E0599`.
warning: `detcore` (lib) generated 1 warning
error: could not compile `detcore` due to previous error; 1 warning emitted

```

**Comment by androm3da** [comment]
$ rustc --version
rustc 1.67.0-nightly (b7bc90fea 2022-11-21)

**Comment by androm3da** [comment]
Sorry - this was caused by a stale `Cargo.lock` file.  Disregard.
